Update Stop_Airflow.yml

diff --git a/.github/workflows/Stop_Airflow.yml b/.github/workflows/Stop_Airflow.yml
--- a/.github/workflows/Stop_Airflow.yml
+++ b/.github/workflows/Stop_Airflow.yml
@@ -11,15 +11,9 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v3
 
-      # Docker Hub 로그인
-      - name: Log in to Docker Hub
-        uses: docker/login-action@v2
-        with:
-          username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_PASSWORD }}
-
-      # Docker 컨테이너 종료
-      - name: Stop Airflow container
+      # 컨테이너 중지
+      - name: Stop Airflow container using Docker Compose
         run: |
-          docker stop my-airflow || echo "Airflow container not found!"
-          echo "Airflow container stopped."
+          cd action_practice 
+          docker-compose stop || echo "Container not found or Docker Compose is not set up!"
+          echo "Airflow container stopped using Docker Compose."
