Update Trigger DAG.yml

diff --git a/.github/workflows/Trigger DAG.yml b/.github/workflows/Trigger DAG.yml
--- a/.github/workflows/Trigger DAG.yml
+++ b/.github/workflows/Trigger DAG.yml
@@ -18,10 +18,10 @@ jobs:
       # Airflow DAG 트리거
       - name: Trigger DAG in Airflow
         run: |
-          docker exec airflow-airflow-webserver-1 airflow dags trigger -d book_mlops || echo "Failed to trigger DAG."
+          docker exec airflow_airflow_webserver_1 airflow dags trigger -d book_mlops || echo "Failed to trigger DAG."
 
       
       # 로그 출력
       - name: Fetch Airflow logs
         run: |
-          docker logs airflow-airflow-webserver-1 2>&1 | grep "Recommended books" || echo "Log message not found"
+          docker logs airflow_airflow_webserver_1 2>&1 | grep "Recommended books" || echo "Log message not found"
