Update Trigger DAG.yml

diff --git a/.github/workflows/Trigger DAG.yml b/.github/workflows/Trigger DAG.yml
--- a/.github/workflows/Trigger DAG.yml
+++ b/.github/workflows/Trigger DAG.yml
@@ -15,22 +15,13 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v3
 
-      # Docker Hub 로그인
-      - name: Log in to Docker Hub
-        uses: docker/login-action@v2
-        with:
-          username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_PASSWORD }}
-
       # Airflow DAG 트리거
       - name: Trigger DAG in Airflow
         run: |
-          docker exec my-airflow airflow dags trigger -d book_recommendation_pipeline || echo "Failed to trigger DAG."
+          docker exec airflow-airflow-webserver-1 airflow dags trigger -d book_mlops || echo "Failed to trigger DAG."
 
-      # 로그 가져오기 (DAG 실행 로그 예시)
-      - name: Fetch logs for DAG task
+      
+      # 로그 출력
+      - name: Fetch Airflow logs
         run: |
-          docker exec my-airflow airflow logs book_recommendation_pipeline task_name --start-date 2025-01-01 --end-date 2025-01-02
-          echo "Logs fetched successfully."
-
-          
+          docker logs airflow-airflow-webserver-1 2>&1 | grep "Recommended books" || echo "Log message not found"
